from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field, field_validator

# ---------- Hotel ----------


class HotelBase(BaseModel):
    name: str
    location: str
    total_rooms: int = Field(gt=0)
    star_rating: float = Field(ge=1, le=5)


class HotelCreate(HotelBase):
    pass


class HotelResponse(HotelBase):
    id: int
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------- Room ----------


class RoomBase(BaseModel):
    room_number: str
    room_type: str
    base_price: float = Field(gt=0)
    max_occupancy: int = Field(gt=0)
    is_available: bool = True


class RoomCreate(RoomBase):
    hotel_id: int


class RoomResponse(RoomBase):
    id: int
    hotel_id: int

    model_config = {"from_attributes": True}


# ---------- Booking ----------


class BookingBase(BaseModel):
    check_in_date: datetime
    check_out_date: datetime
    guest_name: str
    guest_email: Optional[EmailStr] = None
    num_guests: int = Field(gt=0)
    booking_price: float = Field(gt=0)
    base_price: float = Field(gt=0)
    booking_source: str = "direct"

    @field_validator("check_out_date")
    @classmethod
    def check_out_after_check_in(cls, v, info):
        check_in = info.data.get("check_in_date")
        if check_in and v <= check_in:
            raise ValueError("check_out_date must be after check_in_date")
        return v


class BookingCreate(BookingBase):
    hotel_id: int
    room_id: int


class BookingResponse(BookingBase):
    id: int
    hotel_id: int
    room_id: int
    booking_date: datetime
    status: str

    model_config = {"from_attributes": True}


# ---------- DailyMetrics ----------
# System-generated by the metrics calculator (Module 8) — no Create schema,
# only a Response schema for reading pre-aggregated values back out.


class DailyMetricsResponse(BaseModel):
    id: int
    hotel_id: int
    date: datetime
    occupancy_rate: float
    rooms_occupied: int
    rooms_available: int
    total_revenue: float
    average_daily_rate: float
    revenue_per_available_room: float
    booking_count: int
    cancellation_count: int
    calculated_at: datetime

    model_config = {"from_attributes": True}
